webtrigger/controllers/main.py
# -*- coding: utf-8 -*-
# Copyright 2009-2015, Red Hat, Inc.
# License: GPL-2.0+ <http://spdx.org/licenses/GPL-2.0+>

from flask import Blueprint, render_template
from sqlalchemy import desc

from webtrigger import app, db
from webtrigger.controllers import forms
from webtrigger.models import Package, Event, Trigger, Job
from webtrigger.lib.jobschedule import schedule_job


main = Blueprint('main', __name__)

# this isn't the most elegant way to keep the item_types consistent but it
# works for a crummy PoC
item_types = [('koji_build','koji_build'), ('koji_tag','koji_tag'), ('compose','compose')]

@main.route('/')
def index():
    if app.debug:
        app.logger.debug('rendering index')
    jobs = Job.query.all()
    return render_template('index.html', title='Webtrigger Index', jobs=jobs)


@main.route('/package', methods = ["GET", "POST"])
def package():
    pkg_form = forms.PackageForm()

    if pkg_form.validate_on_submit():
        pkg_name = pkg_form.name.data

        app.logger.info("adding package {}".format(pkg_name))
        pkg = Package(pkg_name)
        db.session.add(pkg)
        db.session.commit()

    known_packages = Package.query.all()

    return render_template('package.html', title='Packages', known_packages=known_packages, pkg_form=pkg_form)


@main.route('/trigger', methods = ["GET", "POST"])
def trigger():
    trigger_form = forms.TriggerForm()
    trigger_form.item_type.choices = [('koji_build','koji_build'), ('koji_tag','koji_tag'), ('compose','compose')]
    trigger_form.package.choices = [(p.id, p.name) for p in Package.query.order_by('name').all()]

    if trigger_form.validate_on_submit():
        task_name = trigger_form.task_name.data
        item_type = trigger_form.item_type.data
        package_id = trigger_form.package.data
        repourl = trigger_form.repourl.data
        print("got trigger request for {} ({}), {}, {}".format(task_name, repourl, item_type, package_id))

        # look for package
        package = Package.query.filter_by(id=package_id).first()

        trigger = Trigger(package, item_type, task_name, repourl)

        db.session.add(trigger)
        db.session.commit()

    triggers = Trigger.query.all()
    return render_template('trigger.html', title='Task Triggers', triggers=triggers, trigger_form=trigger_form)


@main.route('/event', methods=['GET', 'POST'])
def event():
    event_form = forms.EventForm()
    event_form.item_type.choices = [('koji_build','koji_build'), ('koji_tag','koji_tag'), ('compose','compose')]
    event_form.package.choices = [(p.id, p.name) for p in Package.query.order_by('name').all()]

    if event_form.validate_on_submit():
        item = event_form.item.data
        item_type = event_form.item_type.data
        package_id = event_form.package.data
        print("got trigger request for {}, {}, {}".format(item, item_type, package_id))

        # look for package
        package = Package.query.filter_by(id=package_id).first()

        event = Event(package, item, item_type)
        db.session.add(event)

        # look for triggers so we can schedule jobs
        triggers = Trigger.query.filter_by(package=package, item_type=item_type).all()

        for trigger in triggers:
            app.logger.info("Scheduling {}({}) for {} ({}) from package {}".format(trigger.task_name, trigger.repourl, item, item_type, package.name))
            newjob = Job(event, trigger)
            db.session.add(newjob)
            if app.config['SCHEDULE']:
                schedule_job(item, item_type, trigger.task_name, trigger.repourl, 'x86_64', use_disposable=True)

        db.session.commit()

        # now that we've got jobs in the db, let's try scheduling them

    elif len(event_form.errors) > 0:
        print event_form.item.errors
        print event_form.item_type.errors
        print event_form.package.errors
        for error in event_form.errors:
            print error

    recent_events = Event.query.order_by(desc(Event.timestamp)).limit(10)

    return render_template('event.html', title='list', event_form=event_form, recent_events=recent_events)

webtrigger/templates/event.html
{% extends "layout.html" %}

{% block body %}
<h1>Webtrigger Events</h1>

Last 10 Events
<table>
    <thead>
        <tr>
            <th>timestamp</th>
            <th>package</th>
            <th>item</th>
            <th>item_type</th>
        </tr>
    </thead>
    <tbody>
        {% for event in recent_events %}
        <tr>
            <td>{{ event.timestamp.strftime('%Y%m%d-%H:%M:%S') }}</td>
            <td>{{ event.package.name }}</td>
            <td>{{ event.item }}</td>
            <td>{{ event.item_type }}</td>
        </tr>
        {% else %}
        <tr>
            <td></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<h3>Create New Event</h3>

<form method="post" action="{{ url_for('main.event') }}">
  {{ event_form.csrf_token }}
  <div class="row">
    <div class="large-6 columns">
        <label>{{ event_form.item.label }}
        {{ event_form.item }}
      </label>
    </div>
    <div class="large-6 columns">
        <label>{{ event_form.item_type.label }}
        {{ event_form.item_type }}
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
        <label>{{ event_form.package.label }}
        {{ event_form.package }}
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-2 columns">
        <input type="submit" value="Create Event">
    </div>
  </div>
</form>


{% endblock %}

webtrigger/templates/index.html
{% extends "layout.html" %}

{% block body %}
<h1>Taskotron Web Trigger</h1>

<p>
This is just an example page for the index
</p>

<h3>Jobs</h3>
<table>
    <thead>
        <tr>
            <th>Timestamp</th>
            <th>Package Name</th>
            <th>item</th>
            <th>item_type</th>
            <th>Check Name</th>
            <th>link</th>
        </tr>
    </thead>
    <tbody>
        {% for job in jobs %}
        <tr>
            <td>{{ job.timestamp.strftime('%Y%m%d-%H:%M:%S') }}</td>
            <td>{{ job.event.package.name }}</td>
            <td>{{ job.event.item }}</td>
            <td>{{ job.event.item_type }}</td>
            <td>{{ job.trigger.check_name }}</td>
            <td><a href="{{ config.EXECDB_URL }}/jobs/{{ job.uuid }}">execdb</a></td>
        </tr>
        {% else %}
        <tr>
            <td></td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}

webtrigger/templates/layout.html
<!doctype html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">

        <meta name="description" content="{{ meta_description }}">
        <meta name="author" content="{{ meta_author }}">

        <!-- Place favicon.ico in the root directory -->
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">


        <link rel="stylesheet" href="{{ url_for('static', filename='css/foundation.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/foundation-icons.css') }}" />
        <script src="{{ url_for('static', filename='js/vendor/modernizr.js') }}"></script>

        {% block jsheader %}
        <script type="text/javascript">
        </script>
        {% endblock %}

        <title>{{ title }}</title>

    </head>


    <body>
        <div class="row">
            <div class="large-12 columns">
                <div class="icon-bar four-up">
                    <a class="item" aria-labelledby="#homelabel" href="{{ url_for('main.index') }}">
                        <i class="fi-home"></i>
                        <label id='homelabel'>Home</label>
                    </a>
                    <a class="item" aria-labelledby="#packagelabel" href="{{ url_for('main.package') }}">
                        <i class="fi-plus"></i>
                        <label id='packagelabel'>Add Package</label>
                    </a>
                    <a class="item" aria-labelledby="#triggerlabel" href="{{ url_for('main.trigger') }}">
                        <i class="fi-wrench"></i>
                        <label id='triggerlabel'>Configure Triggers</label>
                    </a>
                    <a class="item" aria-labelledby="#eventlabel" href="{{ url_for('main.event') }}">
                        <i class="fi-upload-cloud"></i>
                        <label id='eventlabel'>Create Event</label>
                    </a>

                </div>
            </div>
        </div>

        <div class="row">
            <div class="large-12 columns">

                {% block body %}
                <h1> webtrigger Layout</h1>

                <p>
                This is just an example page if the layout is not overridden
                </p>
                {% endblock %}
            </div> <!-- closing main large-12 grid -->
        </div> <!-- closing main row -->
        <script src="js/vendor/jquery.js"></script>
        <script src="js/foundation.min.js"></script>
        <script>
        $(document).foundation();
        </script>
    </body>
</html>

webtrigger/templates/package.html
{% extends "layout.html" %}

{% block body %}
<h1>Known Packages</h1>
<table>
    <thead>
        <tr>
            <th>Package Name</th>
        </tr>
    </thead>
    <tbody>
        {% for package in known_packages %}
        <tr>
            <td>{{ package.name }}</td>
        </tr>
        {% else %}
        <tr>
            <td></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<h3>Add New Package</h3>

<form method="post" action="{{ url_for('main.package') }}">
  {{ pkg_form.csrf_token }}
  <div class="row">
    <div class="large-12 columns">
        <label>{{ pkg_form.name.label }}
        {{ pkg_form.name }}
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-2 columns">
        <input type="submit" value="Add Package">
    </div>
  </div>
</form>
{% endblock %}

webtrigger/templates/trigger.html
{% extends "layout.html" %}

{% block body %}
  <h1>Task Triggers</h1>

<table>
    <thead>
        <tr>
            <th>package</th>
            <th>item_type</th>
            <th>Task Name</th>
            <th>Repo</th>
        </tr>
    </thead>
    <tbody>
        {% for trigger in triggers %}
        <tr>
            <td>{{ trigger.package.name }}</td>
            <td>{{ trigger.item_type }}</td>
            <td>{{ trigger.task_name }}</td>
            <td>{{ trigger.repourl }}</td>
        </tr>
        {% else %}
        <tr>
            <td></td>
        </tr>
        {% endfor %}
    </tbody>
</table>


<h3>Add New Trigger</h3>

<form method="post" action="{{ url_for('main.trigger') }}">
  {{ trigger_form.csrf_token }}
  <div class="row">
    <div class="large-6 columns">
        <label>{{ trigger_form.task_name.label }}
        {{ trigger_form.task_name }}
      </label>
    </div>
    <div class="large-6 columns">
        <label>{{ trigger_form.repourl.label }}
        {{ trigger_form.repourl }}
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-6 columns">
        <label>{{ trigger_form.package.label }}
        {{ trigger_form.package }}
      </label>
    </div>
    <div class="large-6 columns">
        <label>{{ trigger_form.item_type.label }}
        {{ trigger_form.item_type }}
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-2 columns">
        <input type="submit" value="Add Trigger">
    </div>
  </div>
</form>

{% endblock %}